version: '3.3'

services:
  aggregator-application:
    image: aggregator-application:v1
    build: ./aggregator-application
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-application:8761/eureka/
    depends_on:
      - covid-application
      - countries-application
    restart: on-failure

  api-gateway-application:
    image: api-gateway-application:v1
    build: ./api-gateway-application
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-application:8761/eureka/
    ports:
      - '8080:8080'
    depends_on:
      - aggregator-application
    restart: on-failure

  countries-application:
    image: countries-application:v1
    build: ./countries-application
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-application:8761/eureka/
    depends_on:
      - service-discovery-application
    restart: on-failure

  covid-application:
    image: covid-application:v1
    build: ./covid-application
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-application:8761/eureka/
    depends_on:
      - service-discovery-application
    restart: on-failure

  service-discovery-application:
    image: service-discovery-application:v1
    build: ./service-discovery-application
    ports:
      - '8761:8761'
    restart: on-failure