eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8080
spring:
  application:
    name: API-GATEWAY
#zuul:
#  routes:
#    aggregator:
#      path: /information_management/countries/*
#      service-id: aggregator
#      url: aggregator
#      strip-prefix: false
#eureka:
#  instance:
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 6
#ribbon:
#  eureka:
#    enabled: false